version: "3"

services:
  tf_ecs_api:
    container_name: tf_ecs_api
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/app/
    depends_on:
      - tf_ecs_database

  tf_ecs_database:
    image: postgres:14-alpine
    container_name: tf_ecs_database
    ports:
      - 5555:5432
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./pq_volume:/var/lib/postgresql